import React from "react";
import { CssBaseline, ThemeProvider, createTheme, Typography, Box, Grid, } from "@material-ui/core";
import { theme, dark, Loader, Logo, Sidebar, UIContainer, Section, SectionHeading, SectionText, SectionRef, FooterLink, SidebarLink, Code, } from "./components";
import MuiAlert from "@material-ui/lab/Alert";
import { CardNetwork, CardProject } from "./components/Cards";
import Burnr from "./assets/images/Burnr.png";
import MultiDemo from "./assets/images/MultiDemo.png";
import Extension from "./assets/images/NewExtension1.png";
import YourProject from "./assets/images/YourProject.png";
const Alert = (props) => {
    return React.createElement(MuiAlert, Object.assign({ elevation: 6, variant: "filled" }, props));
};
const App = () => {
    return (React.createElement(ThemeProvider, { theme: createTheme(theme) },
        React.createElement(CssBaseline, null),
        React.createElement(Loader, null),
        React.createElement(UIContainer, null,
            React.createElement("div", null,
                React.createElement(Section, null,
                    React.createElement(Typography, { variant: "h1" }, "Run Wasm Light Clients of any Substrate based chain directly in your browser")),
                React.createElement(Section, null,
                    React.createElement(Alert, { severity: "warning" }, "This project is experimental!")),
                React.createElement(Section, null,
                    React.createElement(SectionHeading, { id: "substrate-based-chains", prefix: "1" }, "Substrate-based chains"),
                    React.createElement(SectionText, null, "Substrate is a modular framework for creating use-case optimized blockchains at a low cost, by composing custom or pre-built components. Substrate is the backbone that powers Polkadot, a next-generation, heterogeneous, multi-chain network, and its ecosystem."),
                    React.createElement(SectionRef, { href: "https://www.substrate.io/" }, "substrate.io"),
                    React.createElement(SectionRef, { href: "https://substrate.dev/docs/en/" }, "substrate.dev/docs")),
                React.createElement(Section, null,
                    React.createElement(SectionHeading, { id: "wasm-light-clients", prefix: "2" }, "Wasm Light Clients"),
                    React.createElement(SectionText, null, "Substrate-connect turns a browser into a node on a network allowing end-users of Web3 apps to interact with blockchains directly - without connecting to third-party remote nodes and other servers. Removing intermediary servers between network and its users improves security, simplifies infrastructure of a network and lowers its maintenance costs. Decentralized in-browser light clients are a unique feature of substrate-based networks."),
                    React.createElement(SectionRef, { href: "https://www.parity.io/what-is-a-light-client/" }, "\u201CWhat is a light client and why you should care?\u201D by Thibaut Sardan")),
                React.createElement(Section, null,
                    React.createElement(SectionHeading, { id: "supported-networks", prefix: "3" }, "Well known Networks"),
                    React.createElement(Grid, { container: true },
                        React.createElement(CardNetwork, { title: "Westend", statusProps: { status: "supported" }, linkProps: {
                                href: "https://wiki.polkadot.network/docs/en/maintain-networks#westend-test-network",
                            } }, "Testing environment for Polkadot and Kusama deployments and processes"),
                        React.createElement(CardNetwork, { title: "Kusama", statusProps: { status: "supported" }, linkProps: { href: "https://kusama.network/" } }, "A network built as a risk-taking, fast-moving \u2018canary in the coal mine\u2019 for its cousin Polkadot"),
                        React.createElement(CardNetwork, { title: "Polkadot", statusProps: { status: "supported" }, linkProps: { href: "https://polkadot.network/" } }, "Scalable sharded chain and the first protocol that provides a secure environment for cross-chain composability"),
                        React.createElement(CardNetwork, { title: "Rococo", statusProps: { status: "supported" }, linkProps: {
                                href: "https://polkadot.network/rococo-v1-a-holiday-gift-to-the-polkadot-community/",
                            } }, "Testnet designed for parachains and related technologies: Cumulus and HRMP")),
                    React.createElement(SectionRef, { href: "https://paritytech.github.io/substrate-connect/api/enums/connect_src.WellKnownChain.html" }, "WellKnownChain enumeration docs"),
                    React.createElement(SectionText, null, "You have to provide a well-known chain name (polkadot, ksmcc3, westend2, rococo_v2_2). Note that these are the \"real\" names of the chains rather than the names they are more commonly known as (such as Kusama or Rococo). For example, \"ksmcc3\" is the name of Kusama. This is important for chains which have been hard forked. For example, \"rococo_v2\" and \"rococo_v2_2\" are two different chains.")),
                React.createElement(Section, null,
                    React.createElement(SectionHeading, { id: "getting-started", prefix: "4" }, "Getting Started - Usage through the PolkadotJS Provider"),
                    React.createElement(ThemeProvider, { theme: createTheme(dark) },
                        React.createElement(Code, null, "yarn add @polkadot/rpc-provider"),
                        React.createElement(Code, null, "yarn add @polkadot/api"),
                        React.createElement(Code, { heading: "Simple usage (suported chain)" },
                            React.createElement(Box, null, `import { ScProvider, WellKnownChain } from '@polkadot/rpc-provider/substrate-connect';`),
                            React.createElement(Box, null, `import { ApiPromise } from '@polkadot/api';`),
                            React.createElement(Box, { mt: 2 }, `// Create the provider for a known chain`),
                            React.createElement(Box, null, `const provider = new ScProvider(WellKnownChain.westend2);`),
                            React.createElement(Box, { mt: 2 }, `// Stablish the connection (and catch possible errors)`),
                            React.createElement(Box, null, `await provider.connect()`),
                            React.createElement(Box, { mt: 2 }, `// Create the PolkadotJS api instance`),
                            React.createElement(Box, null, `const api = await ApiPromise.create({ provider });`),
                            React.createElement(Box, { mt: 2 }, `await api.rpc.chain.subscribeNewHeads((lastHeader) => {`),
                            React.createElement(Box, { pl: 3 }, `console.log(lastHeader.hash);`),
                            React.createElement(Box, null, `});`),
                            React.createElement(Box, null, `await api.disconnect();`)),
                        React.createElement(Code, { heading: "Simple usage (custom chain)" },
                            React.createElement(Box, null, `import { ScProvider } from '@polkadot/rpc-provider/substrate-connect';`),
                            React.createElement(Box, null, `import { ApiPromise } from '@polkadot/api';`),
                            React.createElement(Box, null, `import jsonCustomSpec from './jsonCustomSpec.json';`),
                            React.createElement(Box, { mt: 2 }, `// Create the provider for the custom chain`),
                            React.createElement(Box, null, `const customSpec = JSON.stringify(jsonCustomSpec);`),
                            React.createElement(Box, null, `const provider = new ScProvider(customSpec);`),
                            React.createElement(Box, { mt: 2 }, `// Stablish the connection (and catch possible errors)`),
                            React.createElement(Box, null, `await provider.connect()`),
                            React.createElement(Box, { mt: 2 }, `// Create the PolkadotJS api instance`),
                            React.createElement(Box, null, `const api = await ApiPromise.create({ provider });`),
                            React.createElement(Box, { mt: 2 }, `await api.rpc.chain.subscribeNewHeads((lastHeader) => {`),
                            React.createElement(Box, { pl: 3 }, `console.log(lastHeader.hash);`),
                            React.createElement(Box, null, `});`),
                            React.createElement(Box, null, `await api.disconnect();`)),
                        React.createElement(Code, { heading: "Parachains usage" },
                            React.createElement(Box, null, `import { ScProvider, WellKnownChain } from '@polkadot/rpc-provider/substrate-connect';`),
                            React.createElement(Box, null, `import { ApiPromise } from '@polkadot/api';`),
                            React.createElement(Box, null, `import jsonParachainSpec from './jsonParachainSpec.json';`),
                            React.createElement(Box, { mt: 2 }, `// Create the provider for the relay chain`),
                            React.createElement(Box, null, `const relayProvider = new ScProvider(WellKnownChain.westend2);`),
                            React.createElement(Box, { mt: 2 }, `// Create the provider for the parachain. Notice that`),
                            React.createElement(Box, null, `// we must pass the provider of the relay chain as the`),
                            React.createElement(Box, null, `// second argument`),
                            React.createElement(Box, null, `const parachainSpec = JSON.stringify(jsonParachainSpec);`),
                            React.createElement(Box, null, `const provider = new ScProvider(parachainSpec, relayProvider);`),
                            React.createElement(Box, { mt: 2 }, `// Stablish the connection (and catch possible errors)`),
                            React.createElement(Box, null, `await provider.connect()`),
                            React.createElement(Box, { mt: 2 }, `// Create the PolkadotJS api instance`),
                            React.createElement(Box, null, `const api = await ApiPromise.create({ provider });`),
                            React.createElement(Box, { mt: 2 }, `await api.rpc.chain.subscribeNewHeads((lastHeader) => {`),
                            React.createElement(Box, { pl: 3 }, `console.log(lastHeader.hash);`),
                            React.createElement(Box, null, `});`),
                            React.createElement(Box, null, `await api.disconnect();`)))),
                React.createElement(Section, null,
                    React.createElement(SectionHeading, { id: "advanced-usage", prefix: "5" }, "Advanced usage (for library authors)"),
                    React.createElement(ThemeProvider, { theme: createTheme(dark) },
                        React.createElement(Code, null, "yarn add @substrate/connect"),
                        React.createElement(Code, { heading: "Connecting to a `WellKnownChain`" },
                            React.createElement(Box, null, `import { WellKnownChain, createScClient } from '@substrate/connect';`),
                            React.createElement(Box, { mt: 2 }, `// Create the client`),
                            React.createElement(Box, null, `const client = createScClient();`),
                            React.createElement(Box, { mt: 2 }, `// Create the chain connection, while passing the \`jsonRpcCallback\` function. `),
                            React.createElement(Box, null, `const chain = await client.addWellKnownChain(`),
                            React.createElement(Box, { pl: 2 }, `  WellKnownChain.polkadot,`),
                            React.createElement(Box, { pl: 2 }, `  function jsonRpcCallback(response) {`),
                            React.createElement(Box, { pl: 4 }, `    console.log('response', response);`),
                            React.createElement(Box, { pl: 2 }, `  }`),
                            React.createElement(Box, null, `);`),
                            React.createElement(Box, { mt: 2 }, `// send a RpcRequest`),
                            React.createElement(Box, null, `chain.sendJsonRpc(`),
                            React.createElement(Box, { pl: 2 }, `  '{"jsonrpc":"2.0","id":"1","method":"system_health","params":[]}'`),
                            React.createElement(Box, null, `);`)),
                        React.createElement(Code, { heading: "Connecting to a parachain" },
                            React.createElement(Box, null, `import { WellKnownChain, createScClient } from '@substrate/connect';`),
                            React.createElement(Box, null, `import jsonParachainSpec from './jsonParachainSpec.json';`),
                            React.createElement(Box, { mt: 2 }, `// Create the client`),
                            React.createElement(Box, null, `const client = createScClient();`),
                            React.createElement(Box, { mt: 2 }, `// Create the relay chain connection. There is no need to pass a callback`),
                            React.createElement(Box, null, `// function because we will sending and receiving messages through`),
                            React.createElement(Box, null, `// the parachain connection.`),
                            React.createElement(Box, null, `await client.addWellKnownChain(WellKnownChain.westend2);`),
                            React.createElement(Box, { mt: 2 }, `// Create the parachain connection.`),
                            React.createElement(Box, null, `const parachainSpec = JSON.stringify(jsonParachainSpec);`),
                            React.createElement(Box, null, `const chain = await client.addChain(`),
                            React.createElement(Box, { pl: 2 }, `  parachainSpec,`),
                            React.createElement(Box, { pl: 2 }, `  function jsonRpcCallback(response) {`),
                            React.createElement(Box, { pl: 4 }, `    console.log('response', response);`),
                            React.createElement(Box, { pl: 2 }, `  }`),
                            React.createElement(Box, null, `);`),
                            React.createElement(Box, { mt: 2 }, `// send a request`),
                            React.createElement(Box, null, `chain.sendJsonRpc(`),
                            React.createElement(Box, { pl: 2 }, `  '{"jsonrpc":"2.0","id":"1","method":"system_health","params":[]}'`),
                            React.createElement(Box, null, `);`)))),
                React.createElement(Section, null,
                    React.createElement(SectionHeading, { id: "api-docs", prefix: "6" }, "API Documentation"),
                    React.createElement(SectionText, null, "For learning more about substrate-connect`s API and usage follow the link below:"),
                    React.createElement(SectionRef, { href: "https://paritytech.github.io/substrate-connect/api/" }, "Learn more")),
                React.createElement(Section, null,
                    React.createElement(SectionHeading, { id: "extension", prefix: "7" }, "Browser Extension"),
                    React.createElement(SectionText, null, "For in-browser use, Substrate Connect provides a Browser Extension built upon the @substrate/light node module that is running the selected light clients inside the extension so that the end-user does not need to fire up a light node in every browser tab. This will also allow the light-node to keep syncing as long as the browser window stays open."),
                    React.createElement(CardProject, { imageProps: {
                            path: Extension,
                            position: "center center",
                            fullWidth: true,
                        } }),
                    React.createElement(SectionRef, { href: "https://github.com/paritytech/substrate-connect/tree/main/projects/extension" }, "Learn more"),
                    React.createElement(SectionRef, { href: "https://chrome.google.com/webstore/detail/khccbhhbocaaklceanjginbdheafklai" }, "Download for Chrome"),
                    React.createElement(SectionRef, { href: "https://addons.mozilla.org/en-US/firefox/addon/substrate-connect/" }, "Download for Firefox"),
                    React.createElement(SectionRef, { href: "./extension/packed-extension.zip" }, "Download zip")),
                React.createElement(Section, null,
                    React.createElement(SectionHeading, { id: "projects", prefix: "8" }, "Projects"),
                    React.createElement(CardProject, { title: "Burnr", subtitle: "Insecure redeemable wallet", imageProps: { path: Burnr, position: "center top" }, linkProps: { href: "./burnr/" } }),
                    React.createElement(CardProject, { title: "Multi-Demo", subtitle: "Simple Demo that covers multi and para chain examples", imageProps: { path: MultiDemo, position: "center top" }, linkProps: { href: "./demo/" } }),
                    React.createElement(CardProject, { title: "Next Project", imageProps: { path: YourProject } },
                        React.createElement(SectionRef, { href: "https://github.com/paritytech/substrate-connect/blob/main/CONTRIBUTING.md" }, "Contributor\u2019s guide"))),
                React.createElement(ThemeProvider, { theme: createTheme(dark) },
                    React.createElement(Section, { pt: 5, pb: 5 },
                        React.createElement(Box, null,
                            React.createElement(FooterLink, { href: "https://parity.io/" },
                                "\u00A9 ",
                                new Date().getFullYear(),
                                " Parity Technologies"),
                            React.createElement(FooterLink, { href: "https://substrate.dev/terms" }, "Terms & conditions"),
                            React.createElement(FooterLink, { href: "https://www.parity.io/privacy/" }, "Privacy policy"),
                            React.createElement(FooterLink, { href: "https://github.com/paritytech/substrate-connect/issues" }, "Report an issue"),
                            React.createElement(FooterLink, { href: "https://github.com/paritytech/substrate-connect" }, "GitHub"))))),
            React.createElement(Sidebar, null,
                React.createElement(Logo, null),
                React.createElement(SidebarLink, { href: "#substrate-based-chains" }, "Substrate-based chain"),
                React.createElement(SidebarLink, { href: "#wasm-light-clients" }, "Wasm Light Clients"),
                React.createElement(SidebarLink, { href: "#supported-networks" }, "Well known Networks"),
                React.createElement(SidebarLink, { href: "#getting-started" }, "Getting Started"),
                React.createElement(SidebarLink, { href: "#advanced-usage" }, "Advanced usage"),
                React.createElement(SidebarLink, { href: "#api-docs" }, "API Documentation"),
                React.createElement(SidebarLink, { href: "#extension" }, "Browser Extension"),
                React.createElement(SidebarLink, { href: "#projects" }, "Projects")))));
};
export default App;
//# sourceMappingURL=App.js.map