name: Substrate Connect CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        # TODO: re-enable Node 20.x after https://github.com/nodejs/node/pull/49500
        node-version: [16.x, 18.x, "20.5"]

    steps:
    - uses: actions/checkout@v4.1.1
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v3
      with:
        node-version: ${{ matrix.node-version }}
        cache: yarn
    - run: yarn install --immutable
    - run: yarn checkResolutions
    - run: yarn build
    - run: yarn lint
    - run: yarn test

  playwright:
    timeout-minutes: 10
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4.1.1
    - uses: actions/setup-node@v3
      with:
        node-version: 18.x
        cache: yarn
    - run: yarn install --immutable
    - run: yarn build
    - name: Build exentension with Manifest v3
      run: yarn build:m3
      working-directory: ./projects/extension
    - name: Install Playwright Browsers
      run: yarn exec playwright install --with-deps chromium
      working-directory: ./projects/extension
    - name: Run Playwright tests
      run: yarn exec playwright test --project=chromium
      working-directory: ./projects/extension
    - uses: actions/upload-artifact@v3
      if: failure()
      with:
        name: playwright-report
        path: projects/extension/playwright-report/

  all:
    # This dummy job depends on all the mandatory checks. It succeeds if and only if all CI checks
    # are successful.
    needs: [build, playwright]
    runs-on: ubuntu-latest
    steps:
     - run: echo Success
